# -*- coding: utf-8 -*-
"""KDM_ICP1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15hKsvtbQCNL3mGz70tomcZkfYZzYDnbC

**Step 1: Below snippet is to import all the libraries that we are going to use**
"""

import nltk
nltk.download('punkt')
import pandas as pd

"""**Step 2: Connecting to the Google Drive**

"""

from google.colab import drive
drive.mount('/content/drive')

"""**Step 3: Once it connected, read the file as pandas dataframe. To do this we need to copy the file location in the code**


"""

dataset=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/input_file.txt",delimiter="\t")
dataset

"""**Stpe 4: After successfully completing the above steps, we have to perform different operations on the file that we took from drive. Before that, I am converting the data set to text using below snippet**

"""

text= dataset.to_string()
print(text)

"""**Operation 1: Printing the first 75 characters in the text**

"""

print(text[:75]) # It prints the first 75 characters in the data

"""**Operation 2: Sorting the characters in the file and find out the unique characters in that**

"""

t1 = sorted(set(text)) # It sorts the characters 
print(t1)
print('{} unique characters'.format(len(t1))) # Printing the unique characters count

"""**Operation 3: Split the words based on our choice in the file and printing the length**"""

s1 = text.split(".") # It splits the data where ever "." present
s1

"""**Operation 4: Converting the characters to upper case, lower case**"""

l1 = text.swapcase() # it swap all the character cases i.e lower->upper and upper->lower
print(l1)
l2 = text.lower()  # it converts all the characters to lowercase
print(l2)
l3 = text.upper()  # it converts all the characters to uppercase
l3